/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BlogArticle: typeof import('./components/BlogArticle.vue')['default']
    BlogCreate: typeof import('./components/BlogCreate.vue')['default']
    BlogEdit: typeof import('./components/BlogEdit.vue')['default']
    BlogList: typeof import('./components/BlogList.vue')['default']
    ComponentDialog: typeof import('./components/ComponentDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
